import { Header } from '@/components/layout/Header';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import OptimaLtPro from 'next/font/local';
import { Footer } from '@/components/layout/Footer';
import { Aside } from '@/components/sections/Aside';
import { Hero } from '@/components/sections/Hero';
import { Hits } from '@/components/sections/Hits';
import { Awareness } from '@/components/sections/Awareness';
import { Services } from '@/components/sections/Services';
import { BusinessPartners } from '@/components/sections/BusinessPartners';
import { ThemeModule } from '@/components/sections/ThemeModule';
import { Guide } from '@/components/sections/Guide';
import { Partners } from '@/components/sections/Partners';
import { Feedback } from '@/components/sections/Feedback';
import { Thanks } from '@/components/sections/Thanks';
import { NotFound } from '@/components/sections/NotFound';
import { Links } from '@/components/sections/Links';
import { FAQ } from '@/components/sections/FAQ';
import { Contact } from '@/components/sections/Contact';
import RenderBlock from '@/components/RenderBlock';

const optimaLtPro = OptimaLtPro({
    variable: '--accent-font',
    src: [
        {
            path: '../../public/fonts/OptimaLTPro-Roman.woff',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/OptimaLTPro-Medium.woff',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../../public/fonts/OptimaLTPro-DemiBold.woff',
            weight: '600',
            style: 'normal',
        },
    ],
});

const openSans = Open_Sans({
    weight: ['400', '500', '600'],
    subsets: ['latin'],
    variable: '--primary-font',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children, session }) {
    return (
        <html>
            <body
                className={`${openSans.variable} font-sans ${optimaLtPro.variable} font-optima`}
            >
                <div session={session}>
                    <Aside />
                    <Header />
                    <RenderBlock id={64} />
                    <main>{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
