import { Header } from '@/components/layout/Header';
import './globals.css';
import { Open_Sans } from 'next/font/google';
// import OptimaLtPro from 'next/font/local';
import { Footer } from '@/components/layout/Footer';
import NextAuthProvider from './providers/NextAuthProvider';
import { Aside } from '@/components/layout/Aside';
import { Hero } from '@/components/layout/Hero';

// const optimaLtPro = OptimaLtPro({
//     src: '../../public/fonts/OptimaLTPro-Roman.woff',
//     variable: '--accent-font',
//     weight: ['400', '500', '600'],
// });

const openSans = Open_Sans({
    weight: ['400', '500', '600'],
    subsets: ['latin'],
    variable: '--primary-font',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children, session }) {
    return (
        <html>
            <body className={`${openSans.variable} font-sans`}>
                <NextAuthProvider session={session}>
                    <Aside />
                    <Header />
                    <Hero />
                    {children}
                    <Footer />
                </NextAuthProvider>
            </body>
        </html>
    );
}
