import { Header } from '@/components/layout/Header';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import OptimaLtPro from 'next/font/local';
import { Footer } from '@/components/layout/Footer';
import { Aside } from '@/components/layout/Aside';
import { Hero } from '@/components/layout/Hero';
import { Hits } from '@/components/layout/Hits';
import { Awareness } from '@/components/layout/Awareness';
import { Services } from '@/components/layout/Services';
import { BusinessPartners } from '@/components/layout/BusinessPartners';
import { ThemeModule } from '@/components/layout/ThemeModule';
import { Guide } from '@/components/layout/Guide';
import { Partners } from '@/components/layout/Partners';
import { Feedback } from '@/components/layout/Feedback';

const optimaLtPro = OptimaLtPro({
    variable: '--accent-font',
    src: [
        {
            path: '../../public/fonts/OptimaLTPro-Roman.woff',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/OptimaLTPro-Medium.woff',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../../public/fonts/OptimaLTPro-DemiBold.woff',
            weight: '600',
            style: 'normal',
        },
    ],
});

const openSans = Open_Sans({
    weight: ['400', '500', '600'],
    subsets: ['latin'],
    variable: '--primary-font',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children, session }) {
    return (
        <html>
            <body
                className={`${openSans.variable} font-sans ${optimaLtPro.variable} font-optima`}
            >
                <div session={session}>
                    <Aside />
                    {/* <Header /> */}
                    {/* <Hero /> */}
                    <Hits />
                    <Awareness />
                    <Services />
                    <BusinessPartners />
                    <ThemeModule />
                    <Guide />
                    <Partners />
                    <Feedback />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
